name: Publish Web Portfolio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "website" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.0

      - name: Install dependencies
        run: flutter pub get

      - name: Build web release version
        run: flutter build web --release

      - name: Upload web build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout website branch
        uses: actions/checkout@v4
        with:
          ref: website

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: web-build-artifact/

      - name: Copy web build to website branch
        run: |
          cp -r web-build-artifact/. .
          rm -rf web-build-artifact  # Remove o diretório após copiar os arquivos

      - name: Remove old build directory from repository (if exists)
        run: |
          git rm -rf --ignore-unmatch web-build-artifact

      - name: Verify directory structure before commit
        run: ls -la

      - name: Commit and push changes to website branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy new web build" || echo "No changes to commit"
          git push origin website
